### ISSUE TITLE
What's missing?

### ISSUE THREAD

**Issue by Sophivorus** [JeroenDeDauw/reviews#2]
Hi Joroen! I might be able to finish this extension, but could you give me some lead on what's missing? I replaced a few old methods with current ones, but although the extension throws no errors now, it shows no output either (other than the title "Post a review"). Could you help me get started by writing a few words on what's the current status of this? Thanks!

**Comment by JeroenDeDauw** [comment]
Woha - blast from the past. I vaguely recall I had serious problems with getting ratings to show up nicely. That's it I'm afraid

**Comment by Sophivorus** [comment]
Thanks! I'm still not 100% sure I will fix this extension or your other abandoned extension [Ratings](https://www.mediawiki.org/wiki/Extension:Ratings), cheers!

**Comment by JeroenDeDauw** [comment]
Huh. WTF :D I was thinking about Ratings apparently. No idea what this Reviews extension is about then though ...
